services:

  mongo:
    image: mongo
    restart: always
    logging:
      driver: none
    healthcheck:
      test:  echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  backend-test:
    build:
      context: backend
      dockerfile: ../Dockerfile.backend
    environment:
      DB_ADDRESS: mongodb://mongo:27017/mestodb
    command: npm run lint
    restart: 'no'
    depends_on:
      mongo:
        condition: service_healthy

  backend:
    build:
      context: backend
      dockerfile: ../Dockerfile.backend
    environment:
      DB_ADDRESS: mongodb://mongo:27017/mestodb
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - 3000:3000
    healthcheck:
      interval: 10s
      timeout: 2s 
      start_period: 15s 
      retries: 5 
      test: node healthcheck.js

  main-microfrontend:
    build:
      context: frontend/main
      dockerfile: ../../Dockerfile.frontend
    ports:
      - 8080:8080
    depends_on:
      auth-microfrontend:
        condition: service_started
      profile-microfrontend:
        condition: service_started
      card-microfrontend:
        condition: service_started

  auth-microfrontend:
    build:
      context: frontend/auth
      dockerfile: ../../Dockerfile.frontend
    ports:
      - 8081:8081
    depends_on:
      backend:
        condition: service_healthy

  profile-microfrontend:
    build:
      context: frontend/profile
      dockerfile: ../../Dockerfile.frontend
    ports:
      - 8082:8082
    depends_on:
      backend:
        condition: service_healthy

  card-microfrontend:
    build:
      context: frontend/card
      dockerfile: ../../Dockerfile.frontend
    ports:
      - 8083:8083
    depends_on:
      backend:
        condition: service_healthy