FROM node:22-slim as builder
WORKDIR /build
COPY package*.json .
RUN npm install
COPY . .
RUN npm run build

FROM node:22-slim as runner
WORKDIR /app
COPY --from=builder build/package*.json .
COPY --from=builder build/dist dist/
RUN npm install --only=prod
ENTRYPOINT [ "npm", "run" ]
CMD [ "build:start" ]